add1 = open("DBMS\\DBMS_1\\01_myfile.txt","r")
add2 = open("DBMS\\DBMS_1\\01_mysecondfile.txt","r")
cur = open("DBMS\\DBMS_1\\01_mynewfile.txt","w")
cur.write(add1.read())
cur.write('\n')
cur.write(add2.read())
add1.close()
add2.close()
cur.close()