#01. WAP to demonstrate different datatypes in Python
a=1
print(type(a))
b=1.0
print(type(b))
c="python"
print(type(c))
d=1+1j
print(type(d))
e=True
print(type(e))
f=None
print(type(f))
g=range(10)
print(type(g))
h=[a,b,c]
print(type(h))
i=a,b,c
print(type(i))
j={'int':a,'float':b,'str':c}
print(type(j))
k={a,b,c}
print(type(k))
l=frozenset(k)
print(type(l))